In [25]:
import json
import math
import fiona
import folium
import branca.colormap as cm
import requests
import numpy as np
import pandas as pd
import geopandas as gp
from shapely.geometry import Polygon
import urllib.request
from urllib import request
from shapely.geometry import shape, Point
import os
import threading
from rtree import index
import time

In [26]:

def job(num):
     print("子執行緒",num)
threads=[]
for i in range(3):
    threads.append(threading.Thread(target = job ,args=(i,)))
    threads[i].start()

for i in range(3):
    print("主程式",i)
    
for i in threads:
    i.join()
    
print("結束")

子執行緒 0
子執行緒 1
子執行緒 2
主程式 0
主程式 1
主程式 2
結束

In [35]:
#爬蟲 微型感測器

url = 'https://aqi.thu.edu.tw/echarts/getEPAIotData'
json_data = request.urlopen(url).read().decode("utf-8")
json_data = json.loads(json_data);
frame = pd.DataFrame.from_dict(json_data);

frame['areaname']=''
frame

                 datetime   device_id   latitude    longitude pm25 areaname
0     2019-11-02 18:27:10  1858224692  24.975056   121.330402    7
1     2019-11-02 18:28:12  1858300612  24.956991   121.345565  -99
2     2019-11-02 18:27:32  1858495000  25.042832   121.137675  -99
3     2019-11-02 18:26:58  1858569336  24.967298   121.339279    9
4     2019-11-02 18:22:10  1858763627  24.973724   121.332481   12
5     2019-11-02 18:27:20  1858852981  24.972902   121.342242   10
6     2019-11-02 18:27:27  1858981737  24.976159   121.334666   10
7     2019-11-02 18:20:00  1859886331  24.965728   121.332249  -99
8     2019-11-02 18:28:12  1860067717   24.94805   121.341753    9
9     2019-11-02 18:28:16  1860271203  24.956835   121.360893    7
10    2019-11-02 18:28:13  1860464577  24.973736   121.328505   11
11    2019-11-02 18:28:07  1860726455   24.95694   121.358481    8
12    2019-11-02 17:25:15  1860963112  24.954746   121.337874  -99
13    2019-11-02 17:31:45  1861018038  24.950129   121.348118   11
14    2019-11-02 18:27:38  1862163982  24.956971   121.353984    8
15    2019-11-02 17:27:12  1862457890  24.970894   121.345517   10
16    2019-11-02 18:27:49  1862897586   24.97058   121.331179   10
17    2019-11-02 18:27:19  1862971569  24.950401   121.334204    9
18    2019-11-02 18:27:22  1863205278  24.959464   121.333213    7
19    2019-11-02 18:27:20  1863764400    24.9604   121.330078   21
20    2019-11-02 18:27:09  1863877721  24.963708   121.342454    7
21    2019-11-02 18:23:46  1864546032  24.971011   121.336552   12
22    2019-11-02 18:27:47  1864807098  24.953845   121.350925   11
23    2019-11-02 14:51:08  1866611329   24.95083   121.346077   10
24    2019-11-02 18:25:12  1866744702  24.956576   121.337736  -99
25    2019-11-02 18:16:38  1867537158  24.956231   121.352497    9
26    2019-11-02 18:19:12  1868410882  24.960914   121.342878    7
27    2019-11-02 18:25:10  1869361459  24.973444    121.33057   12
28    2019-11-02 18:26:15  1869405703  24.968421   121.330661   10
29    2019-11-02 18:26:12  1869567580  24.965094   121.333579  -99
...                   ...         ...        ...          ...  ...      ...
2777  2019-11-02 18:14:44  7987507173  25.047451  121.1310884    9
2778  2019-11-02 18:14:44  7987608543  25.048755   121.129219    8
2779  2019-11-02 18:14:25  7987793070  25.054866   121.123246    9
2780  2019-11-02 18:14:55  7987855873  25.057495  121.1152785   10
2781  2019-11-02 18:14:58  7987961034  25.046954  121.1111425   11
2782  2019-11-02 18:14:41  7988024089  25.064562   121.120823    8
2783  2019-11-02 18:15:04  7988166360  25.061307  121.1251906    8
2784  2019-11-02 18:14:18  7988259989  25.056992   121.104735   10
2785  2019-11-02 18:14:27  7988395047  25.046122   121.132872    9
2786  2019-11-02 18:14:55  7988461564  25.055194   121.116414   10
2787  2019-11-02 18:14:33  7988598611  25.058884   121.121314    9
2788  2019-11-02 18:15:01  7988629786  25.057596  121.1251142   10
2789  2019-11-02 18:14:26  7988754035   25.05025   121.115985    6
2790  2019-11-02 18:17:56  7988818039  25.056512   121.120024    7
2791  2019-11-02 18:14:33  7988972848   25.05832   121.123008   10
2792  2019-11-02 18:14:52  7989011015  25.050563   121.108035    8
2793  2019-11-02 18:14:38  7989160860  25.047959   121.134063    8
2794  2019-11-02 18:14:55  7989239781  25.053034  121.1158763    9
2795  2019-11-02 18:15:02  7989322672  25.055378  121.1197762   10
2796  2019-11-02 18:15:10  7989455998  25.054342   121.121735    9
2797  2019-11-02 18:14:32  7989549635  25.064154   121.127907   10
2798  2019-11-02 18:14:52  7989902710  23.728264   120.517662   13
2799  2019-11-02 18:14:38  7993228745  25.055072   121.127096   11
2800  2019-11-02 18:14:56  7993385132  25.058023   121.112805   10
2801  2019-11-02 18:14:51  7993448076  25.062125   121.115039   16
2802  2019-11-02 18:14:53  7993504300  25.063242    121.11771   10
2803  2019-11-02 18:14:55  7993682699  25.062113   121.120035    7
2804  2019-11-02 18:18:03  7993788998  25.062335  121.1226841   12
2805  2019-11-02 18:17:51  7993862045  25.067426  121.1267174   10
2806  2019-11-02 18:14:23  7993968814   25.05499   121.125331   12

[2807 rows x 6 columns]

In [51]:
def get_areanamebythread(totaldata):
    totalnum=totaldata  #總執行次數
    Q=int(totalnum/10) #取商數
    R=totalnum%10      #取餘數
    
    for i in range(Q):
        threads = []
        for j in range(10):
            threads.append(threading.Thread(
                target=getareaname,#要執行函數
                args=(frame['longitude'][i*10+j],frame['latitude'][i*10+j],i*10+j)))#要執行函數的參數
            threads[j].start()
        for j in threads:
            j.join()
        print(round(float((i+1)*100/totalnum*10),2),'%')#顯示進度
    
    threads = []
    for i in range(R):
        threads.append(threading.Thread(
            target=getareaname,
            args=(frame['longitude'][Q*10+i],frame['latitude'][Q*10+i],Q*10+i)))
        threads[i].start()
    for j in threads:
        j.join()
    print("100%")#顯示進度

def search(x, y):  #尋找鄉鎮
    global shapes, townnames
    #idx = index.Index()
    #for town_id, shape in shapes.items():
    #idx.insert(town_id,shape.bounds)
    return next((townnames[town_id]  #如果鄉鎮區域包含傳入的經緯度就傳回townnames[town_id]
                 for town_id in shapes #idx.intersection((x,y)) #逐一尋找各鄉鎮
                 if shapes[town_id].contains(Point(x, y))), None)

In [52]:
#找出位於台中的微型感測器


area_append = pd.DataFrame(columns=['areaname'])
area_append['areaname'] = frame['datetime']

def getareaname(lng,lat,num):
   
    lng = float(lng)
    lat = float(lat)
    
    area_append['areaname'][num]=search(float(lng), float(lat))
    return 0

module_dir = os.path.dirname('/home/gh555657/123321/areasearch/')  #取得目前目錄
collection = fiona.open(os.path.join(module_dir,'TOWN_MOI_1070516.shp'))
shapes = {}
townnames = {}

for f in collection:
    town_id =f['properties']['TOWNCODE'] #鄉鎮代碼
    shapes[town_id] = shape(f['geometry'])  #鄉鎮界限經緯度
    townnames[town_id] = f['properties']['COUNTYNAME'] + f['properties']['TOWNNAME']#search函式傳回值
    
t1=time.time()
taiepa=get_areanamebythread(frame.shape[0])
t2=time.time()

print('gevent-time:%s' % str(t2-t1))
frame['areaname']=area_append['areaname']
taichungepa = frame.loc[frame["areaname"].str.contains('台中|臺中')]

0.36 %
0.71 %
1.07 %
1.43 %
1.78 %
2.14 %
2.49 %
2.85 %
3.21 %
3.56 %
3.92 %
4.28 %
4.63 %
4.99 %
5.34 %
5.7 %
6.06 %
6.41 %
6.77 %
7.13 %
7.48 %
7.84 %
8.19 %
8.55 %
8.91 %
9.26 %
9.62 %
9.98 %
10.33 %
10.69 %
11.04 %
11.4 %
11.76 %
12.11 %
12.47 %
12.83 %
13.18 %
13.54 %
13.89 %
14.25 %
14.61 %
14.96 %
15.32 %
15.68 %
16.03 %
16.39 %
16.74 %
17.1 %
17.46 %
17.81 %
18.17 %
18.53 %
18.88 %
19.24 %
19.59 %
19.95 %
20.31 %
20.66 %
21.02 %
21.38 %
21.73 %
22.09 %
22.44 %
22.8 %
23.16 %
23.51 %
23.87 %
24.23 %
24.58 %
24.94 %
25.29 %
25.65 %
26.01 %
26.36 %
26.72 %
27.08 %
27.43 %
27.79 %
28.14 %
28.5 %
28.86 %
29.21 %
29.57 %
29.93 %
30.28 %
30.64 %
30.99 %
31.35 %
31.71 %
32.06 %
32.42 %
32.78 %
33.13 %
33.49 %
33.84 %
34.2 %
34.56 %
34.91 %
35.27 %
35.63 %
35.98 %
36.34 %
36.69 %
37.05 %
37.41 %
37.76 %
38.12 %
38.48 %
38.83 %
39.19 %
39.54 %
39.9 %
40.26 %
40.61 %
40.97 %
41.33 %
41.68 %
42.04 %
42.39 %
42.75 %
43.11 %
43.46 %
43.82 %
44.18 %
44.53 %
44.89 %
45.24 %
45.6 %
45.96 %
46.31 %
46.67 %
47.03 %
47.38 %
47.74 %
48.09 %
48.45 %
48.81 %
49.16 %
49.52 %
49.88 %
50.23 %
50.59 %
50.94 %
51.3 %
51.66 %
52.01 %
52.37 %
52.73 %
53.08 %
53.44 %
53.79 %
54.15 %
54.51 %
54.86 %
55.22 %
55.58 %
55.93 %
56.29 %
56.64 %
57.0 %
57.36 %
57.71 %
58.07 %
58.43 %
58.78 %
59.14 %
59.49 %
59.85 %
60.21 %
60.56 %
60.92 %
61.28 %
61.63 %
61.99 %
62.34 %
62.7 %
63.06 %
63.41 %
63.77 %
64.13 %
64.48 %
64.84 %
65.19 %
65.55 %
65.91 %
66.26 %
66.62 %
66.98 %
67.33 %
67.69 %
68.04 %
68.4 %
68.76 %
69.11 %
69.47 %
69.83 %
70.18 %
70.54 %
70.89 %
71.25 %
71.61 %
71.96 %
72.32 %
72.68 %
73.03 %
73.39 %
73.74 %
74.1 %
74.46 %
74.81 %
75.17 %
75.53 %
75.88 %
76.24 %
76.59 %
76.95 %
77.31 %
77.66 %
78.02 %
78.38 %
78.73 %
79.09 %
79.44 %
79.8 %
80.16 %
80.51 %
80.87 %
81.23 %
81.58 %
81.94 %
82.29 %
82.65 %
83.01 %
83.36 %
83.72 %
84.08 %
84.43 %
84.79 %
85.14 %
85.5 %
85.86 %
86.21 %
86.57 %
86.93 %
87.28 %
87.64 %
87.99 %
88.35 %
88.71 %
89.06 %
89.42 %
89.78 %
90.13 %
90.49 %
90.84 %
91.2 %
91.56 %
91.91 %
92.27 %
92.63 %
92.98 %
93.34 %
93.69 %
94.05 %
94.41 %
94.76 %
95.12 %
95.48 %
95.83 %
96.19 %
96.54 %
96.9 %
97.26 %
97.61 %
97.97 %
98.33 %
98.68 %
99.04 %
99.39 %
99.75 %
100%
gevent-time:20.833659410476685

In [32]:
area_append

     areaname
0      新北市鶯歌區
1      新北市鶯歌區
2      桃園市觀音區
3      新北市鶯歌區
4      新北市鶯歌區
5      新北市鶯歌區
6      新北市鶯歌區
7      新北市鶯歌區
8      新北市鶯歌區
9      新北市鶯歌區
10     新北市鶯歌區
11     新北市鶯歌區
12     新北市鶯歌區
13     新北市鶯歌區
14     新北市鶯歌區
15     新北市鶯歌區
16     新北市鶯歌區
17     新北市鶯歌區
18     新北市鶯歌區
19     新北市鶯歌區
20     新北市鶯歌區
21     新北市鶯歌區
22     新北市鶯歌區
23     新北市鶯歌區
24     新北市鶯歌區
25     新北市鶯歌區
26     新北市鶯歌區
27     新北市鶯歌區
28     新北市鶯歌區
29     新北市鶯歌區
...       ...
2777   桃園市觀音區
2778   桃園市觀音區
2779   桃園市觀音區
2780   桃園市觀音區
2781   桃園市觀音區
2782   桃園市觀音區
2783   桃園市觀音區
2784   桃園市觀音區
2785   桃園市觀音區
2786   桃園市觀音區
2787   桃園市觀音區
2788   桃園市觀音區
2789   桃園市觀音區
2790   桃園市觀音區
2791   桃園市觀音區
2792   桃園市觀音區
2793   桃園市觀音區
2794   桃園市觀音區
2795   桃園市觀音區
2796   桃園市觀音區
2797   桃園市觀音區
2798   雲林縣斗六市
2799   桃園市觀音區
2800   桃園市觀音區
2801   桃園市觀音區
2802   桃園市觀音區
2803   桃園市觀音區
2804   桃園市觀音區
2805   桃園市觀音區
2806   桃園市觀音區

[2807 rows x 1 columns]